// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujgscczzeijqbnwuegal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqZ3NjY3p6ZWlqcWJud3VlZ2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2Njk3NzcsImV4cCI6MjA0OTI0NTc3N30.beYfcCsceKM8u5TErQbfh_W-wSxSywL-t6RxIRcK0lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);